name: send_message_example
description: Demonstrates how to use the send_message plugin.
publish_to: 'none'

environment:
  sdk: '>=2.12.0-259.8.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  send_message:
    path: ../
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

